### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by AJenbo** [julealgon/DiabloCore#35]
Between https://github.com/julealgon/DiabloCore/commit/f721067c0415856d352f6fb424b24fa0aad670b2 and https://github.com/julealgon/DiabloCore/commit/ef06a9ebad3742c1670f91d1347450be1dd21fc5 CI builds seams to have started to fail. Maybe an update of https://github.com/julealgon/DiabloCore/blob/master/.github/workflows/Windows_x64.yml#L12 is enough to fix it, I can't really test it before one of my other PRs are merged as that is required for outsider to have there PRs build by CI

I would suggest registering the project with https://www.appveyor.com/ since there is already a configuration for having it build via VS2019 on there CI: https://github.com/julealgon/DiabloCore/blob/master/appveyor.yml, which probably better match your workflow.

**Comment by julealgon** [comment]
I had noticed CI failing, but to be honest didn't pay much attention to it. It's very likely that the very next changes will already convert the entire thing to C# so I'm not very worried about the cpp builds.

Also, I'm most likely not going to use appveyor as well.

If any of that changes, I'll reopen and look closer into this.
